version: "{build}"

os:
  - Visual Studio 2017
  - Visual Studio 2015

platform:
  - x64
  - x86
  - Win32

configuration:
  - Release
  - Debug
  - RelWithDebInfo

environment:
  PYTHON_PATH: "C:/Python35"

  matrix:
    - generator: Ninja
    - generator: SLN

# xxxnsubtil: this is really ugly
matrix:
  exclude:
    - generator: Ninja
      platform: Win32
    - generator: SLN
      platform: x86

install:
  - git submodule update --init --recursive
  - mkdir build
  - cd build

for:
-
  matrix:
    only:
      - generator: Ninja
  
  before_build:
    - choco install ninja /y
    - set CI_PROJECT_DIR=%APPVEYOR_BUILD_FOLDER%
    - call ../.ci/setup-vs2017.bat
    - cmake --version
    - cl.exe
    - cmake --config %configuration% -G %generator% ..

  build_script:
    - cmake --build .

-
  matrix:
    only:
      - generator: SLN
  
  before_build:
    - cmake --version
    - cmake -A %platform% --config %configuration% ..

  build:
    parallel: true
    project: build/vulkan-sdk.sln
    verbosity: quiet
