version: "{build}"

os:
  - Visual Studio 2017
  - Visual Studio 2015

platform:
  - x64
  - Win32

configuration:
  - Release
  - Debug
  - RelWithDebInfo

environment:
  PYTHON_PATH: "C:/Python35"

  matrix:
    - generator: Ninja
    - generator: SLN

matrix:
  exclude:
    # run only Ninja+RelWithDebInfo 64-bit build on Visual Studio 2015
    - os: Visual Studio 2015
      generator: SLN
    - os: Visual Studio 2015
      configuration: Release
    - os: Visual Studio 2015
      configuration: Debug
    - os: Visual Studio 2015
      platform: Win32
    
    # run only one debug SLN 64-bit build on Visual Studio 2017
    - os: Visual Studio 2017
      generator: SLN
      configuration: Release
    - os: Visual Studio 2017
      generator: SLN
      configuration: Debug
    - os: Visual Studio 2017
      generator: SLN
      platform: Win32

before_build:
  # translate platform into the "architecture" that SLN-based generators expect
  - if "%platform%" == "Win32" ( set arch=x86 )
  - if "%platform%" == "x64" ( set arch=x64 )

  # set up environment variables for VS
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2015" ( call "%VS140COMNTOOLS%/../../vc/vcvarsall.bat" %arch% )
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2017" ( call .ci/setup-vs2017.bat )

  # clone submodules
  - git submodule update --init --recursive

  - mkdir build
  - cd build

  # log the version of cmake and cl
  - cmake --version
  - cl.exe

  # create the build files
  - if "%generator%" == "Ninja" ( set cmake_generator_args=-G Ninja --config %configuration% )
  - if "%generator%" == "SLN" ( set cmake_generator_args=-A %platform% )
  - echo %cmake_generator_args%
  - cmake %cmake_generator_args% ..

for:
-
  matrix:
    only:
      - generator: Ninja

  install:
    - choco install /y ninja

  build_script:
    - cmake --build .

-
  matrix:
    only:
      - generator: SLN

  build:
    parallel: true
    project: build/vulkan-sdk.sln
    verbosity: quiet

test_script:
    # explicitly excluded:
    # * glslang-testsuite (needs glslang inside shaderc to run)
    # * spirv-cross-* (failing)
    # * spirv-tools-copyrights (occasional failures on certain systems?)
    - ctest -j12 -C %configuration% -E "glslang-testsuite|spirv-cross-*|spirv-tools-copyrights"
