variables:
  GIT_STRATEGY: fetch
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build

.windows-build-script:
  script: &windows-build-script
    - set
    - git clean -fdx
    - call %CI_PROJECT_DIR%/.ci/setup-vs2017.bat
    - call %CI_PROJECT_DIR%/.ci/run-windows-build.bat

win64-debug-ninja:
  stage: build
  tags:
    - windows
  variables:
    CMAKE_GENERATOR: "Ninja"
    CMAKE_BUILD_TYPE: "Debug"
    BUILD_ARCH: "x64"
  script: *windows-build-script

win32-debug-ninja:
  stage: build
  tags:
    - windows
  variables:
    CMAKE_GENERATOR: "Ninja"
    CMAKE_BUILD_TYPE: "Debug"
    BUILD_ARCH: "x86"
  script: *windows-build-script

win64-relwithdebinfo-ninja:
  stage: build
  tags:
    - windows
  variables:
    CMAKE_GENERATOR: "Ninja"
    CMAKE_BUILD_TYPE: "RelWithDebInfo"
    BUILD_ARCH: "x64"
  script: *windows-build-script

win32-relwithdebinfo-ninja:
  stage: build
  tags:
    - windows
  variables:
    CMAKE_GENERATOR: "Ninja"
    CMAKE_BUILD_TYPE: "RelWithDebInfo"
    BUILD_ARCH: "x86"
  script: *windows-build-script

win64-release-ninja:
  stage: build
  tags:
    - windows
  variables:
    CMAKE_GENERATOR: "Ninja"
    CMAKE_BUILD_TYPE: "Release"
    BUILD_ARCH: "x64"
  script: *windows-build-script

win32-release-ninja:
  stage: build
  tags:
    - windows
  variables:
    CMAKE_GENERATOR: "Ninja"
    CMAKE_BUILD_TYPE: "Release"
    BUILD_ARCH: "x64"
  script: *windows-build-script

win64-debug-sln:
  stage: build
  tags:
    - windows
  variables:
    CMAKE_GENERATOR: "Visual Studio 15 2017 Win64"
    CMAKE_BUILD_TYPE: "Debug"
    EXTRA_BUILD_ARGS: "-- /m"
  script: *windows-build-script

win32-debug-sln:
  stage: build
  tags:
    - windows
  variables:
    CMAKE_GENERATOR: "Visual Studio 15 2017"
    CMAKE_BUILD_TYPE: "Debug"
    EXTRA_BUILD_ARGS: "-- /m"
  script: *windows-build-script

win64-relwithdebinfo-sln:
  stage: build
  tags:
    - windows
  variables:
    CMAKE_GENERATOR: "Visual Studio 15 2017 Win64"
    CMAKE_BUILD_TYPE: "RelWithDebInfo"
    EXTRA_BUILD_ARGS: "-- /m"
  script: *windows-build-script

win32-relwithdebinfo-sln:
  stage: build
  tags:
    - windows
  variables:
    CMAKE_GENERATOR: "Visual Studio 15 2017"
    CMAKE_BUILD_TYPE: "RelWithDebInfo"
    EXTRA_BUILD_ARGS: "-- /m"
  script: *windows-build-script

win64-release-sln:
  stage: build
  tags:
    - windows
  variables:
    CMAKE_GENERATOR: "Visual Studio 15 2017 Win64"
    CMAKE_BUILD_TYPE: "Release"
    EXTRA_BUILD_ARGS: "-- /m"
  script: *windows-build-script

win32-release-sln:
  stage: build
  tags:
    - windows
  variables:
    CMAKE_GENERATOR: "Visual Studio 15 2017"
    CMAKE_BUILD_TYPE: "Release"
    EXTRA_BUILD_ARGS: "-- /m"
  script: *windows-build-script
