version: "{build}"

os:
  - Visual Studio 2017

platform:
  - x64
  - Win32

configuration:
  - Release
  - Debug
  - RelWithDebInfo

environment:
  PYTHON_PATH: "C:/Python35"

  matrix:
    - CMAKE_GENERATOR: "Ninja"
    - CMAKE_GENERATOR: "Visual Studio 15 2017"
      EXTRA_BUILD_ARGS: "/m"
    - CMAKE_GENERATOR: "Visual Studio 13 2015"
      EXTRA_BUILD_ARGS: "/m"

install:
  - git submodule update --init --recursive

before_build:
  - cmake --version
  - mkdir build
  - cd build
  - cmake -A %PLATFORM% --config %CONFIGURATION% -G %CMAKE_GENERATOR% .. 

build_script:
  - cd build
  - cmake --build . -- %EXTRA_BUILD_ARGS%
