version: "{build}"

os:
  - Visual Studio 2017

platform:
  - x64

configuration:
  - Release
  - Debug
  - RelWithDebInfo

environment:
  PYTHON_PATH: "C:/Python35"

install:
  - git submodule update --init --recursive

before_build:
  - cmake --version
  - mkdir build
  - cd build
  - cmake -G "Visual Studio 15 2017 Win64" ..

build:
  parallel: true
  project: build/vulkan-sdk.sln
  verbosity: quiet
